INSERT INTO public."tag" ("name", "order", "color") VALUES ('Їжа', 0, 'green');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Продукти', 1, 'lime');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Транспорт', 2, 'blue');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Дім', 3, 'gray');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Хоббі', 4, 'purple');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Машина', 5, 'darkblue');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Офіс', 6, 'slateblue');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Здоров’я', 7, 'lightgreen');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Краса та догляд', 8, 'violet');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Розваги', 9, 'purple');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Улюбленці', 10, 'gold');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Подарунки', 11, 'pink');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Алкоголь', 12, 'darkred');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Тютюн', 13, 'brown');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Підписки', 14, 'orange');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Інше', 15, 'pink');
