INSERT INTO public."tag" ("name", "order", "color") VALUES ('Їжа', 0, 'green');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Продукти', 1, 'lime');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Транспорт', 2, 'blue');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Дім', 3, 'gray');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Хоббі', 4, 'purple');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Машина', 5, 'darkgrey');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Мотоцикл', 6, 'darkblue');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Офіс', 7, 'slateblue');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Здоровʼя', 8, 'lightgreen');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Краса та догляд', 9, 'violet');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Розваги', 10, 'purple');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Улюбленці', 11, 'gold');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Подарунки', 12, 'pink');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Одяг', 13, 'lightblue');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Алкоголь', 14, 'darkred');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Тютюн', 15, 'brown');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Підписки', 16, 'orange');
INSERT INTO public."tag" ("name", "order", "color") VALUES ('Інше', 17, 'pink');
